public class ExpresstionDemo {

    
  public static Integer a = 8;
    public static Integer b = 2;
    
    public static void getData()
    {
       
        
        
       System.debug(a<<=b);
        //a=a+b;
        //System.debug(a);
        
        //System.debug(a = b);
        
       // System.debug(a+=b); // a=a+b=>10
        
          // System.debug(a*=b);// 16>> 10*2=?20       
        
       
        
        
        
        
        
        
    }
    
    
    
}